name: multiple-trigger
run-name: multiple-trigger
on:
  label:
    types: [created, edited]
jobs:
  multiple-triggers:
    runs-on: ubuntu-latest
    steps:
      - run: echo "there was a label"âˆ
      
